bookstore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("inventory.urls", namespace="book")),
]

inventory/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add/$', views.add_books, name='add'),
    url(r'^$', views.list_books, name='list'),
]

inventory/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class BookStore(models.Model):
    """
    Book Model 

    Fields (title, author, category, date_created and date_updated)
    
    """
    category_choices = (
        ('art','Art'),
        ('nature','Nature'),
        ('history','History'),
        ('music','Music'),
    )
    title = models.CharField(max_length=270)
    author = models.CharField(max_length=100)
    category = models.CharField(max_length=50, choices=category_choices)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True, auto_now_add=False)


    def __str__(self):
        # Support Python 3 for object represantation
        return "{}".format(self.title)

    def __unicode__(self):
        # Support Python 2 for object represantation
        return "{}".format(self.title)

    def get_absolute_url(self):
        # After saving point the redirect to index page
        return reverse('book:list')

    # Order results returned basing on the last record in the database
    class Meta:
        ordering = ['-id']

inventory/forms.py
from django.forms import ModelForm

from .models import BookStore

class BookForm(ModelForm):
    """
    Form for Adding Books 
    It will contain title, author and category

    """
    class Meta:
        model = BookStore
        fields = ['title', 'author', 'category',]

inventory/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .models import BookStore
from .forms import BookForm

# Create your views here.


def list_books(request):
    books = BookStore.objects.all()
    param = request.POST.get('category')
    name = request.POST.get('search_name')
    if param is not None and name is not None:
        books = seachItem(param, name)

    context = {
        'title': 'List of Books',
        'books': books,
        'noResults': "No books found"
    }
    return render(request, 'list.html', context)

def add_books(request):
    book_form = BookForm(request.POST or None)

    if book_form.is_valid():
        instance = book_form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title': 'Add a new book',
        'form': book_form
    }
    return render(request, 'add_book.html', context)

def seachItem(param, name):
    # method to search depending on what a user entered
    if param == 'category':
        result = BookStore.objects.filter(category__iexact=str(name))
    else:
        result = BookStore.objects.filter(title__icontains=str(name))
    return result

templates/add_book.html
{% extends "base.html" %}

{% block content %}
    
    <div>
        {{ title }}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-default" name="" value="Add Book">
        </form>
    </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="container">
        <div class="col-sm-8 col-sm-offset-2">
             <ul class="nav nav-pills">
                <li role="presentation"><a href="{% url 'book:list' %}">Home</a></li>
                <li role="presentation"><a href="{% url 'book:add' %}">Add new Book</a></li>
            </ul>
            <br/>
            {% block content %}
        
            {% endblock content %}
        </div>
        </div>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>

templates/list.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        
        {% include "search.html" %}
        <br/>
        {% for book in books %}
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading">{{ book.title }}</h4>
                    <p class="list-group-item-text">
                        Author: {{ book.author }} <br/>
                        Category: {{ book.category }}
                    </p>
                </a>
            </div>
        {% endfor %}

        {% if not books %}
            <p class="bg-danger">
                {{ noResults }}
            </p>
        {% endif %}
        
    </div>
{% endblock content %}

templates/search.html
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<form action="" method="POST" class="form-inline">
				{% csrf_token %}
				<div class="form-group">
					<input type="text" name="search_name" class="form-control" placeholder="Enter name or category">
				</div>
				<select name='category' class="form-control">
            <option value="book">Book Name</option>
            <option value="category">Category</option>
        </select>
				<input type="submit" class="btn btn-primary" value="Search">
			</form>
		</div>
	</div>
</div>